service: analytico
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: staging
  lambdaHashingVersion: 20201221
  environment:
    ENV: ${opt:stage}

functions:
  hello:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users/create
          method: POST
    environment:
      SECRET: ${ssm:Analytico-${opt:stage, 'staging'}-createUser-secret}

plugins:
  - serverless-offline

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: Analytico-${opt:stage, 'staging'}-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S