service: analytico
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: staging
  lambdaHashingVersion: 20201221
  environment:
    ENV: ${opt:stage}

functions:
  create_user:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: POST
    environment:
      SECRET: ${ssm:Analytico-${opt:stage, 'staging'}-createUser-secret}
  create_project:
    handler: handler.createWebsiteAnalyticsProject
    events:
      - httpApi:
          path: /projects
          method: POST
  list_project:
    handler: handler.listWebsiteAnalyticsProjects
    events:
      - httpApi:
          path: /projects
          method: GET

plugins:
  - serverless-offline

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: Analytico-${opt:stage, 'staging'}-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
    WebsiteAnalyticsProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: website
            KeyType: RANGE
        TableName: Analytico-${opt:stage, 'stage'}-websiteAnalyticsProjects
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: website
            AttributeType: S